[[rule]]
toolName = "run_shell_command"
commandRegex = "setup.sh"
decision = "ask_user"
priority = 100
modes = ["plan"]

[[rule]]
toolName = "run_shell_command"
commandPrefix = ["npm install", "npm i"]
decision = "ask_user"
priority = 100
modes = ["plan"]

[[rule]]
toolName = "run_shell_command"
commandRegex = "modern-web"
decision = "ask_user"
priority = 100
modes = ["plan"]
