import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { fileURLToPath } from "url";
import { Embedder } from "../src/lib/embedder.js";
import { Store, type UseCase as StoreUseCase } from "../src/lib/store.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, "..");
const GUIDES_DIR = path.join(ROOT_DIR, "src/guides");
const BUILD_GUIDES_DIR = path.join(ROOT_DIR, "build/guides");
const DATA_DIR = path.join(ROOT_DIR, "src/data");
const OUTPUT_FILE = path.join(DATA_DIR, "use-cases.gen.ts");

interface UseCase {
  id: string;
  description: string;
  category: string;
}

// Ensure build/guides exists
if (!fs.existsSync(BUILD_GUIDES_DIR)) {
  fs.mkdirSync(BUILD_GUIDES_DIR, { recursive: true });
}

async function processGuides() {
  const useCases: UseCase[] = [];
  const storeUseCases: StoreUseCase[] = [];
  const categories = fs.readdirSync(GUIDES_DIR);

  console.log("Initializing Embedder...");
  const embedder = Embedder.getInstance();
  await embedder.init();

  console.log("Initializing Store...");
  const store = new Store();

  for (const category of categories) {
    const categoryDir = path.join(GUIDES_DIR, category);
    if (!fs.statSync(categoryDir).isDirectory()) continue;

    // Create category dir in build/guides
    const buildCategoryDir = path.join(BUILD_GUIDES_DIR, category);
    if (!fs.existsSync(buildCategoryDir)) {
      fs.mkdirSync(buildCategoryDir, { recursive: true });
    }

    const files = fs.readdirSync(categoryDir);
    for (const file of files) {
      if (!file.endsWith(".md")) continue;

      const id = path.basename(file, ".md");
      const filePath = path.join(categoryDir, file);
      const content = fs.readFileSync(filePath, "utf-8");

      const { data, content: markdownBody } = matter(content);

      if (!data.description) {
        console.warn(`Warning: Missing metadata in ${filePath}`);
        continue;
      }

      useCases.push({
        id,
        description: data.description,
        category,
      });

      console.log(`Embedding ${id}...`);
      const embeddingText = `${id} (${category}): ${data.description}`;
      console.log(`Embedding ${id} ("${embeddingText}")...`);
      const vector = await embedder.embed(embeddingText);

      storeUseCases.push({
        id,
        description: data.description,
        category,
        vector
      });

      // Write clean markdown to build dir
      const buildFilePath = path.join(buildCategoryDir, file);
      fs.writeFileSync(buildFilePath, markdownBody.trimStart());
    }
  }

  // Generate TypeScript file
  const tsContent = `// This file is auto-generated by scripts/build-guides.ts
export interface UseCase {
  id: string;
  description: string;
  category: string;
}

export const USE_CASES: UseCase[] = ${JSON.stringify(useCases, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`Generated ${useCases.length} use cases to ${OUTPUT_FILE}`);

  console.log("Upserting to LanceDB...");
  await store.upsert(storeUseCases);
  console.log("Vector store updated.");
}

processGuides().catch(console.error);
